on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /

jobs:
  build-static:
    uses: ./.github/workflows/build.yml
  deploy-to-R2:
    runs-on: ubuntu-latest
    environment: production
    needs: build-static
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: static-build-output
          path: output

      - name: List files
        run: ls -la output/

      - name: Upload files to R2
        working-directory: output
        run: aws s3 sync --delete . s3://5wc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_REGION: auto
