on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /

jobs:
  deploy-to-R2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: static-build-output
      - name: List all files
        run: ls -lah
#      - name: Upload files to R2
#        run: aws s3 sync ./out s3://5wc
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}

